#Exercício 1 :
n1 = int(input("numero 1:"))
n2 = int(input("numero 2:"))
n3 = int(input("numero 3:"))

media = (n1+n2+n3)/3
print("Média: ", media)

#Exercício 2:

num = int(input("Digite um número para saber seu antecessor e sucessor: "))
ant = (num - 1 )
suc = (num + 1 )

print("Número:{}, Antecessor: {}, Sucessor: {}".format(num,ant,suc))

# Exercício 3:

n1 = int(input("some dois números: "))
n2 = int(input("some dois números: "))
soma = n1 + n2
print("SOMA = ", soma)

# Exercício 4:

num = int(input("descubra a terça parte desse número: "))
ter = num/3
print(ter)
